### ISSUE TITLE
A fix for Croc Legend of the Gobbos

### ISSUE THREAD

**Issue by AfterBurnerTeirusu** [tpunix/SAROO#181]
This is a fix, not an issue. I just have no idea where this should be posted.
Add this to your saroo config file to make Croc Legend of the Gobbos playable. It does not work without patching. (The game has to show the loading screens for 3D models to load correctly)
Croc Legend of the Gobbos (US)

[T-5029H-50 V1.000]

sector_delay=1000

**Comment by yzbss** [comment]
This game I test without setting can go directly into, but there will be a role without a head problem, check, it should be the original code of the game has a bug, and vdp1 register and memory relationship

This bug also occurs when using fenrir mode and Satiator to enter the game directly. The solution is to enter the bios menu first and then enter the game

**Comment by AfterBurnerTeirusu** [comment]
Did you read my message? The fix is right there...

**Comment by nullpointer-br** [comment]
> This game I test without setting can go directly into, but there will be a role without a head problem, check, it should be the original code of the game has a bug, and vdp1 register and memory relationship
> 
> This bug also occurs when using fenrir mode and Satiator to enter the game directly. The solution is to enter the bios menu first and then enter the game

Possible explanation by Outside998 from youtube video:

"For the curious, this bug happens in the first print of the Saturn version, because one of the chips does not get initialized at start up of the game. Every Saturn software had to initialize the chips it needed in software. The CD player happens to use that chip for the visuals of the two cubes, which is why it works then.

Now, why was that bug not found before shipping? Because the game was only tested on Saturn dev kits, and those initialize all chips, no matter if needed or not. Only after shipping did they realize the mistake"

**Comment by ragingchaos** [comment]
> silly menu shenanigans.

@AfterBurnerTeirusu The fix Sega shipped with PAL copies of the game was a piece or paper with instructions to boot to the CD Player Menu and then load the game. The dev is saying its not an error with Saroo, it's working as intended just like it does on other ODEs and real discs. 

Have you tried the play_delay setting instead of sector_delay? 

Maybe it only needs a delay at boot time to initialize VDP and that is something @yzbss and the other devs could consider adding.

**Comment by AfterBurnerTeirusu** [comment]
> > silly menu shenanigans.
> 
> @AfterBurnerTeirusu The fix Sega shipped with PAL copies of the game was a piece or paper with instructions to boot to the CD Player Menu and then load the game. The dev is saying its not an error with Saroo, it's working as intended just like it does on other ODEs and real discs.
> 
> Have you tried the play_delay setting instead of sector_delay?
> 
> Maybe it only needs a delay at boot time to initialize VDP and that is something @yzbss and the other devs could consider adding.

I'm not a developer, but my sector delay fixes the issue. That is THE REASON I SHARED IT HERE.
And yes, I own a PAL copy of the game with the small paper. My fix just makes the game easier to boot on a saroo. How many times do I have to repeat it here? Should I log in weekly and repeat the same sentence over and over again?

**Comment by ragingchaos** [comment]
This is Saroo's issue tracker. You have found a workaround for your unique situation and I don't think anyone is confused there but Saroo didn't cause the error. What you have is a request for Saroo to add a patch to this game not a fix.

I've tested the game and also don't have that problem so I can't test play_delay, but I do think it's unnecessary to force a sector_delay on everyone via a firmware update if everyone doesn't need it.

If Croc doesn't properly initialize the hardware at boot then it's not Saroo's fault, but it would be nice if Saroo could patch it by making sure it the hardware is initialized before running the game.

**Comment by AfterBurnerTeirusu** [comment]
> This is Saroo's issue tracker. You have found a workaround for your unique situation and I don't think anyone is confused there but Saroo didn't cause the error. What you have is a request for Saroo to add a patch to this game not a fix.
> 
> I've tested the game and also don't have that problem so I can't test play_delay, but I do think it's unnecessary to force a sector_delay on everyone via a firmware update if everyone doesn't need it.
> 
> If Croc doesn't properly initialize the hardware at boot then it's not Saroo's fault, but it would be nice if Saroo could patch it by making sure it the hardware is initialized before running the game.

Lmao I never came here to shit on the product. I love it. I just had no idea where to add new solutions for issues. A normal customer is not going to know how this stuff works, so it would be a great idea to add new fixes to the default config file. I just have no idea where to send fixes on this website, so I put them here. Not my problem if the dev is hard to reach, or if the official documentation is in a language most global users cannot read.

**Comment by ragingchaos** [comment]
This isn’t the place for general opinions about language barriers and documentation; it’s for reporting bugs directly related to Saroo.

The developers here aren’t selling a product, no customer support should be expected from them.

The developers are not hard to reach, you got an immediate reply from YZB. You chose to ignore his input and question his expertise instead. Documentation issues don’t justify misusing the issue tracker.

The problem here isn’t with Saroo—it’s with how the Saturn initializes hardware when booting Croc. A game-specific boot delay might help, and YZB/TPU might consider it if they have time, but with the attitude being displayed here I wouldn't bother.

**Comment by yzbss** [comment]
If you're having problems playing some games on saroo but other people don't have problems, then you need to think about whether it's the sd card or the saroo hardware or some other problem with the saturn console, because other people have no problems running the game with the same firmware


I was interested in the bugs in saturn's original games, like this one

Here's a bug video
https://www.youtube.com/watch?v=O67H89nx0HA

Just a quick test, copy the following parameters into saroocfg and run the game to see if there are any bugs

Note that it must be the first game that starts with power on, if you have played other games before, then this bug will not appear unless you turn off the power and wait for more than 5 minutes before restarting

#Croc - Legend of the Gobbos (USA/Europe)
[T-5029H-50V1.000]
M_25c7fffe=ffff

**Comment by AfterBurnerTeirusu** [comment]
Closing this "issue" I was just looking for a place to send fixes. Nothing more, nothing else.

**Comment by AfterBurnerTeirusu** [comment]
> #Croc - Legend of the Gobbos (USA/Europe) [T-5029H-50V1.000] M_25c7fffe=ffff

This fix works well. Thank you.
