### ISSUE TITLE
Error on Bug! (US) [GM-81004 V1.017]

### ISSUE THREAD

**Issue by odiaboeeu** [tpunix/SAROO#48]
Hi, Even in this latest firmware version 0.3, the game crashes as soon as it starts the first stage

Tests were done using the delay sector from 1000 to 8000 and nothing changed

**Comment by atds55** [comment]
Here the first stage worked with this configuration:
# BUG
[GM-81004  V1.017]
sector_delay=1000

**Comment by odiaboeeu** [comment]
In the American version it doesn't work even though it has a delay sector

**Comment by atds55** [comment]
> Na versão americana não funciona mesmo tendo setor de delay

Here it works.
https://youtu.be/cFsVuRzphZY

https://github.com/tpunix/SAROO/assets/72902338/36bf6a2f-7b9a-4c77-a2d4-b352571975ca

**Comment by odiaboeeu** [comment]
What exactly is the iso name of the redump you are using? Only if it's some different version

**Comment by atds55** [comment]
> Qual é exatamente o nome iso do redump que você está usando? Só se for alguma versão diferente
I'm using redump version GM-81004 V1.017 (multi bin).
Take a look and test with the saroocfg.txt file I made available.

**Comment by odiaboeeu** [comment]
I need the name that's in the file, I'm going to download it again

**Comment by atds55** [comment]
> I need the name that's in the file, I'm going to download it again

Bug! (USA).zip

![image](https://github.com/tpunix/SAROO/assets/72902338/4cf962e8-77f6-4f72-b2d6-002e5fdc16aa)

**Comment by odiaboeeu** [comment]
You have two versions of the redump that have an R in the file name that doesn't work

**Comment by atds55** [comment]
> It has two versions of the redump that have an R in the file name that doesn't work

Make sure you are putting the correct number of spaces between the game id and version in saroocfg.txt. Between GM-81004 and V1.017 there are 2 spaces, if you put a different number of spaces the sector_delay will not work, in the case of the Bug! It has to be 2 spaces, because that's how it is in the game.

Each 20 shown in hexadicimal is a space, as shown in the image below, there are two 20s between the id and the version, so there are 2 spaces.

![image](https://github.com/tpunix/SAROO/assets/72902338/fafe0639-a4fe-4599-87b7-8ad2790205ac)

**Comment by odiaboeeu** [comment]
@tpunix Does it really matter to saroo how many spaces are between the game's code and its version?

**Comment by odiaboeeu** [comment]
It only works exactly with 1k delay it was before with 2k and above 1k it doesn't work

The version with R I didn't see that it has a different code so it didn't catch on, I'll close the issue 

Ideally, it would be to put this game in the official CFG @tpunix
